version: '2'

volumes:
    symfony_logs:
        driver: local
    symfony_cache:
        driver: local
    nginx_logs:
        driver: local


services:
    db:
        image: mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
    php-fpm-nginx:
        build: .
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
            - symfony_logs:/var/www/symfony/app/logs
            - symfony_cache:/var/www/symfony/app/cache
            - nginx_logs:/var/log/nginx